throw error when init.R is not present in code for predefined stack

diff --git a/acc_worker/k8_gateway_actions/predefined_stacks/Dockerfile.R4_4 b/acc_worker/k8_gateway_actions/predefined_stacks/Dockerfile.R4_4
--- a/acc_worker/k8_gateway_actions/predefined_stacks/Dockerfile.R4_4
+++ b/acc_worker/k8_gateway_actions/predefined_stacks/Dockerfile.R4_4
@@ -19,8 +19,11 @@ WORKDIR /code
 # Copy the local files into the container
 COPY . /code
 
-# If init.R exists, run it at build time
-RUN if [ -f /code/init.R ]; then Rscript /code/init.R; fi
+RUN if [ -f /code/init.R ]; then \
+    Rscript /code/init.R; \
+    else \
+    echo "Error: /code/init.R not found!" && exit 1; \
+    fi
 
 # Default command: start an interactive R session
 CMD ["R"]
